---
title: "R Notebook"
output: html_notebook
---

## Kenton food example
```{r}
#### Kenton food example
sales=c(11,17,16,14,15,12,10,15,19,11,23,20,18,17,27,33,22,26,28)
design=c(rep(1,5),rep(2,5),rep(3,4),rep(4,5))
cbind(sales,design)
```

##ANOVA table: single factor
```{r}
myaov=aov(sales~factor(design))
summary(myaov)
```

```{r}

plot(myaov$fit,myaov$res)
qqnorm(myaov$res)
qqline(myaov$res)
```

```{r}
shapiro.test(myaov$res)
```

```{r}
means=tapply(sales, design, mean)### treatment mean
means
```

```{r}
tapply(sales, design, sd)### treatment sd
```

```{r}
predict(myaov,interval = "confidence", level = .95)
```

### 95% C.I. for mean of design 1
```{r}
lwr=14.6-qt(1-.05/2,df=15)*sqrt(10.55/5) # lwr=11.50433
upr=14.6+qt(1-.05/2,df=15)*sqrt(10.55/5) # upr=17.69567
c(lwr,upr)
```

```{r}
MSE=anova(myaov)$Mean[2]
MSE
```

```{r}
nsize= tapply(sales, design, length) ## treatment size
nsize
```

### 95% C.I. for mean_1-mean_2
```{r}
lwr_21=(means[2]-means[1])-(1/sqrt(2))*qtukey(.95,4,15)*sqrt(MSE*(1/nsize[1]+1/nsize[2]))
upr_21=(means[2]-means[1])+(1/sqrt(2))*qtukey(.95,4,15)*sqrt(MSE*(1/nsize[1]+1/nsize[2]))
c(lwr_21,upr_21)
```

### all-pairwise comparison
```{r}
design=factor(design)
result=aov(sales~design)
TukeyHSD(result,"design",conf.level=.95)
```

